version: '3.8'
services:
  nesttuts:
    image: postgres:13
    container_name: nesttuts-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nesttuts
    networks:
      - nesttuts

networks:
  nesttuts:
